services:
  app:
    build: ./server
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: uvicorn main:app --port 8000 --host 0.0.0.0
  db:
    build: ./sql
    restart: always
    environment:
      MYSQL_DATABASE: 
      MYSQL_ROOT_PASSWORD: msql1234
    ports:
      - "33006:3306"