services:
  db:
    build: ./sql
    container_name: base
    restart: always
    environment:
      # MYSQL_USER: root
      MYSQL_DATABASE: transact
      MYSQL_ROOT_PASSWORD: msql1234
    # healthcheck:
    #   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    #   timeout: 20s
    #   retries: 10
    command:
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION 
    ports:
      - "3008:3306"
    volumes:
      - mysql-config:/etc/mysql/my.cnf
  data:
    build: ./data
    env_file: .env  
    container_name: data
    ports:
      - "8001:8001"
    depends_on:
      - db
      # db:
      #   condition: service_healthy
    healthcheck:
      test: "curl -f http://localhost:8001/health"
    command: uvicorn db:app --port 8001 --host 0.0.0.0
  app:
    build: ./server
    container_name: app
    restart: always
    tty: true
    env_file: .env  
    ports:
      - "8000:8000"
    depends_on:
      data:
        condition: service_healthy
    healthcheck:
      test: "curl -f http://localhost:8000/health"
    command: uvicorn main:app --port 8000 --host 0.0.0.0
  client: 
    build: ./client
    container_name: client
    depends_on:
      app:
        condition: service_healthy
    restart: always
    ports:
      - "5173:5173"
    command: npm run dev

volumes:
  mysql-config: