name: server
channels:
    - conda-forge
    - anaconda
    - defaults
dependencies:
    - python=3.10
    - pandas=2.2.2
    - numpy=1.26.4
    - pip
    - pip:  
        - sqlalchemy
        - PyMySQL
        - fastapi[standard]
        - uvicorn[standard]