name: torchdev
channels:
    - pytorch
    - nvidia
    - conda-forge
    - anaconda
    - defaults
dependencies:
    - python=3.10
    - pytorch=2.3.1
    - pytorch-cuda=12.1
    - pandas=2.2.2
    - numpy=1.26.4
    - ipykernel=6.29.5
    - scipy=1.14.0
    - scikit-learn=1.5.1
    - Pillow=9.3.0
    - tqdm=4.66.5
    - pip
    - pip:  
        - tensorboard
        - yacs==0.1.8
        - matplotlib==3.9.0
        - seaborn==0.13.2
        - termplotlib==0.3.9